"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bot, ChevronRight, Clock3, LogOut, Mail, MessageSquare, RefreshCw, ShieldCheck, User, Users } from "lucide-react";

type SessionRow={session_id:string;visitor_hash:string|null;user_agent:string|null;referrer:string|null;created_at:string;last_active_at:string;message_count:number};
type MessageRow={id:string;session_id:string;role:"user"|"assistant"|"system";content:string;provider:string|null;model:string|null;latency_ms:number|null;status:string;created_at:string};
type EventRow={id:string;session_id:string|null;event_type:string;provider:string|null;model:string|null;latency_ms:number|null;metadata:Record<string,unknown>;created_at:string};
type LeadRow={id:string;session_id:string|null;email:string;message:string;status:string;created_at:string};
type ControlData={admin:{email:string};metrics:{sessions:number;activeToday:number;messagesToday:number;avgResponseMs:number|null;failures:number;leads:number;providerUsage:Record<string,number>};sessions:SessionRow[];messages:MessageRow[];events:EventRow[];leads:LeadRow[];selectedSession:string|null};

const RED="#D62E37";
const DISPLAY_FONT='"Arial Narrow","Helvetica Neue Condensed","Roboto Condensed","Arial",sans-serif';
const fmt=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const shortId=(value:string)=>value.length>12?`${value.slice(0,6)}…${value.slice(-4)}`:value;

function EnvelopeMark({small=false}:{small?:boolean}){return <svg width={small?20:30} height={small?10:15} viewBox="0 0 34 17" aria-hidden="true"><polygon points="0,17 7,0 34,0 27,17" fill={RED}/></svg>}
function Backdrop(){return <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute -inset-x-[8%] inset-y-0 bg-grid-pattern opacity-[0.30]"/><div className="absolute left-[18%] top-[7%] h-[250px] w-[250px] rotate-45 rounded-[7px] bg-white/40"/><div className="absolute left-[48%] top-[18%] h-[330px] w-[330px] rotate-45 rounded-[7px] bg-[#d9d9db]/32"/><div className="absolute right-[4%] top-[5%] h-[270px] w-[270px] rotate-45 rounded-[7px] bg-white/46"/></div>}
function Heading({eyebrow,title,meta}:{eyebrow:string;title:string;meta?:string}){return <div className="relative flex items-start justify-between gap-3 border-b border-[#0b1220]/10 px-4 py-3"><div><div className="mb-2 flex items-center gap-2"><EnvelopeMark small/><span className="text-[9px] font-semibold uppercase tracking-[.22em] text-[#D62E37]">{eyebrow}</span></div><h2 style={{fontFamily:DISPLAY_FONT,fontStretch:"condensed"}} className="text-[24px] font-bold uppercase leading-none tracking-[-.035em] text-[#08101f]">{title}</h2></div>{meta&&<span className="text-[11px] text-[#697384]">{meta}</span>}</div>}
function Metric({label,value,icon:Icon,accent=false}:{label:string;value:string|number;icon:typeof Activity;accent?:boolean}){return <div className="relative min-h-[112px] overflow-hidden rounded-[7px] border border-[#0b1220]/10 bg-white/70 px-4 py-3 shadow-[0_5px_15px_rgba(8,16,31,.035)]"><div className="absolute right-0 top-0 h-14 w-20 [clip-path:polygon(30%_0,100%_0,100%_100%,0_100%)] bg-[#08101f]/[0.035]"/><div className="mb-3 flex items-center justify-between"><span className="text-[9px] font-semibold uppercase tracking-[.21em] text-[#747d8b]">{label}</span><Icon size={14} color={accent?RED:"#687282"}/></div><div style={{fontFamily:DISPLAY_FONT,fontStretch:"condensed"}} className={`text-[40px] font-bold leading-none tracking-[-.055em] ${accent?"text-[#D62E37]":"text-[#08101f]"}`}>{value}</div></div>}
function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`relative overflow-hidden rounded-[7px] border border-[#0b1220]/10 bg-[rgba(238,238,240,.88)] shadow-[0_7px_20px_rgba(8,16,31,.04)] ${className}`}>{children}</section>}

export default function ControlRoomEditorial(){
 const [data,setData]=useState<ControlData|null>(null);const [loading,setLoading]=useState(true);const [authRequired,setAuthRequired]=useState(false);const [error,setError]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [signingIn,setSigningIn]=useState(false);const [selectedSession,setSelectedSession]=useState<string|null>(null);
 const loadData=useCallback(async(session?:string|null)=>{setLoading(true);setError("");try{const q=session?`?session=${encodeURIComponent(session)}`:"";const r=await fetch(`/zero-control/api/data${q}`,{cache:"no-store"});if(r.status===401){setData(null);setAuthRequired(true);return}if(!r.ok)throw new Error("Failed to load Control Room data.");const p=await r.json() as ControlData;setData(p);setAuthRequired(false)}catch(e){setError(e instanceof Error?e.message:"Something went wrong.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void loadData()},[loadData]);
 async function handleLogin(e:FormEvent){e.preventDefault();setSigningIn(true);setError("");try{const r=await fetch("/zero-control/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const p=await r.json() as{error?:string};if(!r.ok)throw new Error(p.error||"Access denied.");setPassword("");await loadData()}catch(err){setError(err instanceof Error?err.message:"Access denied.")}finally{setSigningIn(false)}}
 async function logout(){await fetch("/zero-control/api/logout",{method:"POST"});setData(null);setSelectedSession(null);setAuthRequired(true)}
 async function select(id:string){setSelectedSession(id);await loadData(id)}
 const providers=useMemo(()=>Object.entries(data?.metrics.providerUsage??{}).sort((a,b)=>b[1]-a[1]),[data]);

 if(authRequired&&!data)return <main className="relative min-h-screen overflow-hidden bg-[#efefef] text-[#08101f]"><Backdrop/><div className="relative flex min-h-screen items-center justify-center px-4"><div className="w-full max-w-[500px] rounded-[7px] border border-[#0b1220]/10 bg-[#f5f5f5]/92 shadow-[0_18px_50px_rgba(8,16,31,.07)]"><div className="flex items-start justify-between border-b border-[#0b1220]/10 p-5"><div><div className="mb-3 flex items-center gap-2"><EnvelopeMark/><span className="text-[9px] font-semibold uppercase tracking-[.23em] text-[#D62E37]">Restricted access</span></div><h1 style={{fontFamily:DISPLAY_FONT,fontStretch:"condensed"}} className="text-[36px] font-bold uppercase leading-none tracking-[-.045em]">ZERO CONTROL</h1><p className="mt-2 max-w-md text-[13px] leading-5 text-[#667181]">Private observability for chatbot sessions, messages, model usage and inbound leads.</p></div><ShieldCheck size={20} color={RED}/></div><form onSubmit={handleLogin} className="grid gap-3 p-5"><label className="grid gap-2 text-[9px] font-semibold uppercase tracking-[.21em] text-[#6b7585]">Admin email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-[7px] border border-[#0b1220]/10 bg-white/80 px-3 py-2.5 text-sm normal-case tracking-normal text-[#08101f] outline-none focus:border-[#D62E37]"/></label><label className="grid gap-2 text-[9px] font-semibold uppercase tracking-[.21em] text-[#6b7585]">Password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-[7px] border border-[#0b1220]/10 bg-white/80 px-3 py-2.5 text-sm normal-case tracking-normal text-[#08101f] outline-none focus:border-[#D62E37]"/></label>{error&&<p className="text-sm text-[#D62E37]">{error}</p>}<button disabled={signingIn} className="rounded-[7px] bg-[#08101f] px-4 py-3 text-[10px] font-semibold uppercase tracking-[.21em] text-white hover:bg-[#D62E37] disabled:opacity-50">{signingIn?"Authenticating":"Enter control room"}</button></form></div></div></main>;
 if(loading&&!data)return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#efefef]"><Backdrop/><RefreshCw className="relative animate-spin" color={RED}/></main>;
 if(!data)return null;
 const selected=data.sessions.find(s=>s.session_id===selectedSession)??data.sessions[0]??null;const totalProvider=providers.reduce((sum,[,v])=>sum+v,0)||1;
 return <main className="relative min-h-screen overflow-hidden bg-[#efefef] text-[#08101f]"><Backdrop/><div className="relative mx-auto max-w-[1720px] px-4 py-4 lg:px-6">
  <header className="mb-4 flex flex-col gap-3 border-b border-[#0b1220]/10 pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><EnvelopeMark/><h1 style={{fontFamily:DISPLAY_FONT,fontStretch:"condensed"}} className="text-[34px] font-bold uppercase leading-none tracking-[-.05em]">ZERO <span className="text-[#D62E37]">CONTROL</span></h1></div><p className="mt-2 pl-[42px] text-[13px] text-[#667181]">Private observability · {data.admin.email}</p></div><div className="flex gap-2"><button onClick={()=>void loadData(selectedSession)} className="flex items-center gap-2 rounded-[7px] border border-[#0b1220]/10 bg-white/60 px-3 py-2 text-[9px] font-semibold uppercase tracking-[.19em] hover:border-[#D62E37] hover:text-[#D62E37]"><RefreshCw size={12} className={loading?"animate-spin":""}/>Refresh</button><button onClick={()=>void logout()} className="flex items-center gap-2 rounded-[7px] border border-[#0b1220]/10 bg-white/60 px-3 py-2 text-[9px] font-semibold uppercase tracking-[.19em] hover:border-[#D62E37] hover:text-[#D62E37]"><LogOut size={12}/>Exit</button></div></header>
  {error&&<div className="mb-3 rounded-[7px] border-l-2 border-[#D62E37] bg-white/55 px-3 py-2 text-sm text-[#b21f27]">{error}</div>}
  <section className="mb-4 grid gap-2.5 md:grid-cols-2 xl:grid-cols-6"><Metric label="Sessions" value={data.metrics.sessions} icon={Users}/><Metric label="Active today" value={data.metrics.activeToday} icon={Activity}/><Metric label="Messages" value={data.metrics.messagesToday} icon={MessageSquare}/><Metric label="Avg response" value={data.metrics.avgResponseMs?`${(data.metrics.avgResponseMs/1000).toFixed(2)}s`:"—"} icon={Clock3} accent/><Metric label="Failures" value={data.metrics.failures} icon={AlertTriangle} accent={data.metrics.failures>0}/><Metric label="Leads" value={data.metrics.leads} icon={Mail}/></section>
  <section className="grid gap-3 xl:grid-cols-[290px_minmax(0,1fr)_320px]">
   <Panel className="min-h-[620px]"><Heading eyebrow="Sessions" title="Recent visitors" meta={`${data.sessions.length}`}/><div className="max-h-[560px] overflow-y-auto">{data.sessions.map((s,i)=>{const active=(selectedSession??data.sessions[0]?.session_id)===s.session_id;return <button key={s.session_id} onClick={()=>void select(s.session_id)} className={`relative grid w-full grid-cols-[26px_1fr_auto] gap-2.5 border-b border-[#0b1220]/8 px-4 py-3.5 text-left transition ${active?"bg-[#D62E37]/[0.07]":"hover:bg-white/55"}`}>{active&&<span className="absolute inset-y-0 left-0 w-[3px] bg-[#D62E37]"/>}<span className="pt-0.5 text-[9px] font-semibold text-[#818a97]">{String(i+1).padStart(2,"0")}</span><div><div className="text-[13px] font-semibold">{shortId(s.session_id)}</div><div className="mt-1 text-[11px] text-[#747e8d]">{fmt(s.last_active_at)}</div><div className="mt-2 text-[10px] text-[#8a929e]">{s.message_count} messages{s.visitor_hash?` · UID ${s.visitor_hash.slice(0,7)}`:""}</div></div><ChevronRight size={13} color={active?RED:"#8b94a1"}/></button>})}</div></Panel>
   <Panel className="min-h-[620px]"><Heading eyebrow="Conversation" title={selected?`Session ${shortId(selected.session_id)}`:"No session"} meta={selected?`${selected.message_count} messages`:undefined}/>{selected&&<div className="border-b border-[#0b1220]/10 px-4 py-2 text-[11px] text-[#727c8c]">Last active {fmt(selected.last_active_at)}</div>}<div className="max-h-[560px] space-y-4 overflow-y-auto p-4">{[...data.messages].reverse().map(m=><div key={m.id} className={m.role==="user"?"ml-auto max-w-[320px]":"max-w-[88%]"}><div className="mb-1.5 flex items-center gap-2 text-[9px] uppercase tracking-[.15em] text-[#7b8492]"><span className="flex h-6 w-6 items-center justify-center rounded-[7px] border border-[#0b1220]/10 bg-white/65">{m.role==="assistant"?<Bot size={12} color={RED}/>:<User size={12}/>}</span><strong className="text-[#08101f]">{m.role==="assistant"?"ZERO":"Visitor"}</strong>{m.provider&&<span>{m.provider}</span>}{m.latency_ms!=null&&<span>{m.latency_ms}ms</span>}<span>{fmt(m.created_at)}</span></div><div className={`rounded-[7px] border px-4 py-3 text-[14px] leading-6 shadow-[0_4px_12px_rgba(8,16,31,.02)] ${m.role==="user"?"border-[#D62E37]/20 bg-[#D62E37]/[0.08]":"border-[#0b1220]/10 bg-white/75 text-[#263142]"}`}><p className="whitespace-pre-wrap">{m.content}</p></div></div>)}{!data.messages.length&&<p className="text-sm text-[#737d8c]">No messages in this view.</p>}</div></Panel>
   <div className="space-y-3"><Panel><Heading eyebrow="Providers" title="Model usage"/><div className="space-y-3 p-4">{providers.map(([provider,count])=>{const pct=Math.round(count/totalProvider*100);return <div key={provider}><div className="mb-1.5 flex justify-between text-[13px]"><strong>{provider}</strong><span className="text-[#6d7786]">{count} · {pct}%</span></div><div className="h-[4px] rounded-[7px] bg-[#d4d8de]"><div className="h-full rounded-[7px] bg-[#D62E37]" style={{width:`${pct}%`}}/></div></div>})}{!providers.length&&<p className="text-sm text-[#737d8c]">No provider telemetry.</p>}</div></Panel>
   <Panel><Heading eyebrow="Events" title="Latest activity"/><div className="divide-y divide-[#0b1220]/8">{data.events.slice(0,8).map(ev=><div key={ev.id} className="px-4 py-3"><div className="flex justify-between gap-3 text-[13px]"><strong>{ev.event_type}</strong>{ev.latency_ms!=null&&<span className="text-[#D62E37]">{ev.latency_ms}ms</span>}</div><p className="mt-1 text-[11px] text-[#75808f]">{ev.provider||"system"} · {fmt(ev.created_at)}</p></div>)}{!data.events.length&&<p className="p-4 text-sm text-[#737d8c]">No events yet.</p>}</div></Panel>
   <Panel><Heading eyebrow="Leads" title="Inbound contacts" meta={`${data.leads.length}`}/><div className="divide-y divide-[#0b1220]/8">{data.leads.slice(0,5).map(lead=><div key={lead.id} className="px-4 py-3"><div className="text-[13px] font-semibold">{lead.email}</div><p className="mt-1 text-[11px] leading-5 text-[#75808f]">{lead.message}</p></div>)}{!data.leads.length&&<p className="p-4 text-sm text-[#737d8c]">No leads captured yet.</p>}</div></Panel></div>
  </section>
 </div></main>;
}
